# Generated by Django 2.1.15 on 2021-05-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='料号')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='品名')),
                ('sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='整机SN')),
                ('board_sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='主板SN')),
                ('statu', models.IntegerField(blank=True, null=True, verbose_name='维修状态')),
                ('be_overdue', models.IntegerField(blank=True, null=True, verbose_name='是否过保')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('repair_time', models.DateTimeField(blank=True, null=True, verbose_name='修复时间')),
            ],
            options={
                'db_table': 'repair',
                'managed': True,
            },
        ),
    ]
