# Generated by Django 2.1.15 on 2021-05-17 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IQC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='物料名称')),
                ('material_sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='料号')),
                ('arrive_time', models.DateTimeField(blank=True, null=True, verbose_name='来料时间')),
                ('appearance', models.IntegerField(blank=True, choices=[(1, '合格'), (0, '不合格')], default='不合格', null=True, verbose_name='外观检测')),
                ('arrive_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='来料数量')),
                ('bad_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='不良数量')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
            ],
            options={
                'db_table': 'IQC',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='料号')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='品名')),
                ('part_or_complete', models.IntegerField(blank=True, choices=[(1, '部件'), (0, '整机')], default='整机', null=True, verbose_name='部件/征集')),
                ('collect_money', models.IntegerField(blank=True, choices=[(1, '是'), (0, '否')], default='是', null=True, verbose_name='是否要收款')),
                ('collect_money_num', models.CharField(blank=True, max_length=255, null=True, verbose_name='需要收款价格')),
                ('sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='整机SN')),
                ('board_sn', models.CharField(blank=True, max_length=255, null=True, verbose_name='主板SN')),
                ('statu', models.IntegerField(blank=True, choices=[(2, '已接收'), (1, '维修中'), (0, '已修复')], default='已接收', null=True, verbose_name='维修状态')),
                ('be_overdue', models.IntegerField(blank=True, choices=[(1, '已过保'), (0, '未过保')], default='未过保', null=True, verbose_name='是否过保')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='接收时间')),
                ('repair_time', models.DateTimeField(blank=True, null=True, verbose_name='修复时间')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='交出时间')),
            ],
            options={
                'db_table': 'repair',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据1')),
                ('test2', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据2')),
                ('test3', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据3')),
                ('test4', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据4')),
                ('test5', models.CharField(blank=True, max_length=255, null=True, verbose_name='测试数据5')),
            ],
            options={
                'db_table': 'test',
                'managed': True,
            },
        ),
    ]
