# Generated by Django 2.1.15 on 2021-05-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0002_ware_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='out_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='料号')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('numbers', models.CharField(blank=True, max_length=255, null=True, verbose_name='数量')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='客户')),
                ('out_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='出货地址')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='出货时间')),
            ],
            options={
                'db_table': 'out_record',
                'managed': True,
            },
        ),
    ]
