# Generated by Django 2.1.15 on 2021-05-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0003_out_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='in_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='料号')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名称')),
                ('numbers', models.CharField(blank=True, max_length=255, null=True, verbose_name='数量')),
                ('supplier', models.CharField(blank=True, max_length=255, null=True, verbose_name='供应商')),
                ('in_time', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
            ],
            options={
                'db_table': 'in_record',
                'managed': True,
            },
        ),
    ]
